# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hiroshi Horii
#title: Postdoctoral researcher
email: hiroshi.horii@univ-orleans.fr
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Hiro06190
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a currently postdoctoral researcher at the [Institut Denis Poisson](https://www.idpoisson.fr/) in Université d’Orléans with [Nils Berglund](https://www.idpoisson.fr/berglund/) and [Julien Barré](https://www.idpoisson.fr/barre/). In this position, I am studying the periodic behavior of a dynamical system and the derivation of a macroscopic equation by using a microscopic model.
  
  
  I did my Ph.D. at [LPSM](https://www.lpsm.paris/) in Université Paris Cité with [Raphaël Lefevere](https://www.lpsm.paris/users/lefevere/index) and [Takahiro Nemoto](https://sites.google.com/view/takahiro-nemoto) on finite-time large deviation theory and a heavy-tailed renewal process.
  
  Here is my [Ph.D. thesis](https://Hiro06190.github.io/HiroshiHorii.github.io/Doctoral_dissertation_Horii.pdf).
  
  
content:


  - title: Research interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am interested in mathematical physics (or applied mathematics) topics. In particular, I am working on statistical mechanics and probability theory. More specific topics are the following :
      
        - Non-equilibrium statistical physics, The application of finite time large deviation theory to understand non-equilibrium phenomena.
        
        - Heavy-tailed renewal process and anomalous fluctuations, Finite-time large deviation theory with heavy-tailed stochastic processes.
        
        - The derivation of macroscopic equations by using microscopic models.
        
        - Studying the dynamical systems, stochastic processes, bifurcation theory, the method of characteristic, and numerical simulation.
        
        - Studying universal property in machine learning methods.
        
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      
        - <font size="4.5" style="font-weight: bold;">Large Time Asymptotic of Heavy Tailed Renewal Processes.</font>
          
          Journal of Statistical Physics 186, 11 [[link]](https://link.springer.com/article/10.1007/s10955-021-02856-5)
        
        - <font size="4.5" style="font-weight: bold;">Anomalous fluctuations of renewal-reward processes with heavy-tailed distributions</font>
          
          PHYSICAL REVIEW E 106 (3), 034130[[link]](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.106.034130)
        
        I have experience that I joined nuclear physics experiment.
        - <font size="4.5" style="font-weight: bold;">Chiral symmetry restoration at high matter density observed in pionic atoms</font>
          
          Nature Physics 19 (6), 788-793[[link]](https://www.nature.com/articles/s41567-023-02001-x)
        
        - <font size="4.5" style="font-weight: bold;">Precision spectroscopy of pionic atoms and chiral symmetry in nuclei</font>
          
          EPJ Web of Conferences 130, 01017[[link]](https://www.epj-conferences.org/articles/epjconf/pdf/2016/25/epjconf_meson2016_01017.pdf)
        


      
      
  - title: Simulations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Analysis of the virus spreading COVID-19 with a renewal process
        link: https://hiro06190-repo-untitled6-xdak8i.streamlit.app/
        # link_text: Project Website
        
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)

        description: | # this will include new lines to allow paragraphs
             I also have studied the initial growth of the epidemic curve of Covid-19 by using a stochastic model. This stochastic model is based on a heavy-tailed renewal process. The COVID-19 data is from Johns Hopkins University data site.
             
      - layout: left
        title: Analysis of the virus spreading covid-19 with a renewal process
        link: https://hiro06190-repo-untitled6-xdak8i.streamlit.app/
        # link_text: Project Website
        
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)

        description: | # this will include new lines to allow paragraphs
             I also have studied the initial growth of the epidemic curve of Covid-19 by using a stochastic model. This stochastic model is based on a heavy-tailed renewal process. The COVID-19 data is from Johns Hopkins University data site.
             
  - title: Teaching
    layout: text
    content: | # this will include new lines to allow paragraphs
      
        - 2014: Teaching Assistant for Numerical simulation course at University of Tokyo




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
